# Generated by Django 4.0.6 on 2023-04-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=50)),
                ('detail', models.TextField(max_length=50)),
            ],
        ),
    ]
