# Generated by Django 4.0.6 on 2023-05-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_coupon_discount_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount1',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount2',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Percent', 'Percent')], default='', max_length=20),
        ),
    ]
