from django.urls import path, include
from ecomapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index' ),
    path('newadd/', views.newadd, name='newadd' ),
    path('newadd/<slug:data>', views.newadd, name='newadddata' ),
    path('bestsell/', views.bestsell, name='bestsell' ),
    path('product-detail/<int:pk>', views.product_detail, name='product-detail' ),
    path('fashion/', views.fashion, name='fashion' ),
    path('jewellery/', views.jewellery, name='jewellery' ),
    path('electronic/', views.electronic, name='electronic' ),
    path('mobiles/', views.mobiles, name='mobiles' ),
    path('laptops/', views.laptops, name='laptops' ),
    path('watches/', views.watches, name='watches' ),
    path('topwear/', views.topwear, name='topwear' ),
    path('bottomwear/', views.bottomwear, name='bottomwear' ),
    path('electronic/<slug:data>', views.electronic, name='electronicdata'),
    path('mobiles/<slug:data>', views.mobiles, name='mobilesdata'),
    path('laptops/<slug:data>', views.laptops, name='laptopsdata'),
    path('fashion/<slug:data>', views.fashion, name='fashiondata'),
    path('watches/<slug:data>', views.watches, name='watchesdata'),
    path('jewellery/<slug:data>', views.jewellery, name='jewellerydata'),
    path('topwear/<slug:data>', views.topwear, name='topweardata'),
    path('bottomwear/<slug:data>', views.bottomwear, name='bottomweardata'),
    path('cosmetics/', views.cosmetics, name='cosmetics' ),
    path('fashion/', views.fashion, name='fashion' ),
    path('buy/', views.buy_now, name='buy-now'),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('orders/', views.orders, name='orders'),
    path('pluscart/', views.pluscart),
    path('minuscart/', views.minuscart),
    path('removecart/', views.removecart),
    path('itemadded/', views.itemadded),
    path('search/', views.search, name='search'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('terms/', views.terms, name='terms'),
    path('customer/', views.customer, name='customer'),
    path('profile/', views.profile, name='profile'),
    path('address/', views.address, name='address'),
    path('deladd/<str:pk>', views.deladd, name='deladd'),
    path('editadd/<str:pk>', views.editadd, name='editadd'),
    path('updateadd/', views.editadd, name='updateadd'),
    path('cancelorder/<str:pk>', views.cancelorder, name='cancelorder'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)